import {Arrow,Footer,Header,services,stages} from "./components";
import LifecycleHero from "./lifecycle-hero";
import DiscoveryComingSoon from "./discovery-coming-soon";
const audiences=["Founders & Scaleups","SMEs & Service Businesses","Research & Innovation Teams","AI Product Teams","Investors & Boards","Healthcare & Regulated Organisations"];
export default function Home(){return <><Header/><main>
 <LifecycleHero/>
 <section className="warm"><div className="wrap compact"><p className="eyebrow">Built for organisations moving from ambition to practical delivery</p><div className="audiences">{audiences.map(x=><span key={x}>{x}</span>)}</div><Arrow href="/who-we-help">Explore Who We Help</Arrow></div></section>
 <section className="wrap section split"><div><p className="eyebrow">Why AIVLAB</p><h2>AI ambition is everywhere. Practical AI systems are still difficult to build.</h2></div><p className="lead-copy">Many organisations have promising ideas, valuable data or early prototypes, but lack a clear path through product definition, engineering, validation, deployment and governance. AIVLAB connects these missing pieces.</p><div className="principles">{[["Clarity before investment","Identify the right problem, data requirements, risks and first MVP."],["Complete systems","Connect models with users, workflows, APIs, interfaces and monitoring."],["Proof-led delivery","Create working assets, evaluation evidence and reusable documentation."],["Governance by design","Include privacy, traceability, oversight and uncertainty handling from the beginning."]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
 <section className="wrap section"><div className="section-head"><div><p className="eyebrow">What AIVLAB helps you do</p><h2>End-to-end AI support, from discovery to governed delivery</h2></div><p>Start with a focused assessment or engage across strategy, development, validation, deployment and ongoing technical leadership.</p></div><div className="rows">{services.map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><a href="/services">↗</a></article>)}</div></section>
 <section className="warm"><div className="wrap compact"><p className="eyebrow">A practical path from first question to working system</p><div className="stages">{stages.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Clarify the problem, users and value.","Define product, data, architecture and controls.","Create the simplest credible system.","Test reliability, usability and failure modes.","Prepare infrastructure, monitoring and handover.","Maintain accountability and continuous evaluation."][i]}</p></article>)}</div></div></section>
 <section className="discovery wrap"><div><p className="eyebrow pale">Start with discovery</p><h2>Not sure where AI fits in your organisation?</h2><p>The AIVLAB AI Discovery Agent is being prepared to turn your workflows, challenges, data, risks and 90-day goals into an initial AI Opportunity Snapshot.</p></div><div><ul><li>Prioritised AI opportunities</li><li>Value, feasibility and readiness signals</li><li>Recommended first MVP and technical direction</li><li>Risk, governance and human-oversight considerations</li><li>Suggested 30/60/90-day action plan</li></ul><DiscoveryComingSoon className="btn light">Run AI Discovery Agent</DiscoveryComingSoon></div></section>
 <section className="wrap section"><div className="section-head"><div><p className="eyebrow">Technical Lab & proof assets</p><h2>Practical examples, not just AI claims</h2></div><p>Reusable demonstrators and evaluation patterns showing how AI systems can be built, tested, governed and monitored.</p></div><div className="proofs"><article><span>In development</span><h3>AI Discovery Agent</h3><p>A structured workflow designed to convert organisational context into an initial AI Opportunity Snapshot.</p><DiscoveryComingSoon className="arrow discovery-text-button">View project <span>↗</span></DiscoveryComingSoon></article><article><span>Technical prototype</span><h3>Proteomics Clinical Index Engine</h3><p>A governed demonstrator connecting synthetic proteomics inputs to scoring, clinician reporting and technical audit records.</p><Arrow href="https://github.com/alirizwands/proteomics-clinical-index-engine">View project</Arrow></article><article><span>Lab framework</span><h3>RAG Quality Evaluator</h3><p>A reusable framework for groundedness, citation accuracy, relevance, hallucination risk and reliability.</p><Arrow href="/technical-lab">View project</Arrow></article></div></section>
 <section className="warm"><div className="wrap section about-strip"><div><p className="eyebrow">About us</p><h2>Research depth. Product delivery. Responsible AI systems.</h2></div><div><p className="lead-copy">AIVLAB is a team of AI, data, product and delivery experts with combined research and development experience spanning more than two decades, including more than a decade dedicated to applied AI.</p><p>Our experience covers the complete path from research and problem discovery to engineering, validation, secure deployment, governance and commercialisation.</p><Arrow href="/about">About AIVLAB</Arrow></div></div></section>
 <section className="wrap final"><p className="eyebrow">Your next step</p><h2>Find the right next step for your AI opportunity.</h2><p>Use the AI Discovery Agent for a structured starting point, or share your challenge directly with AIVLAB.</p><div className="actions centered"><DiscoveryComingSoon className="btn">Run AI Discovery Agent</DiscoveryComingSoon><Arrow href="/contact">Share Your AI Challenge</Arrow></div></section>
 </main><Footer/></>}
